  - name: Stop Mysql Service
    shell: /etc/init.d/mysqld stop
    ignore_errors: yes
    when: ansible_os_family == "RedHat" and ansible_distribution_version|int >=6
  - name: Delete Mysql Boot Start Script
    shell: chkconfig --del mysqld
    ignore_errors: yes
    when: ansible_os_family == "RedHat" and ansible_distribution_version|int >=6
  - name: Delete Mysql Dir And Socket
    shell: rm -rf {{ mysql_basedir }} {{ mysql_datadir }} /tmp/mysql.sock /usr/bin/mysql /data/mysql
    when: ansible_os_family == "RedHat" and ansible_distribution_version|int >=6
  - name: Delete Mysql User
    shell: userdel {{ mysql_user }}
    ignore_errors: yes
    when: ansible_os_family == "RedHat" and ansible_distribution_version|int >=6
  - name: Delete Mysql Service Start Script
    shell: rm -rf /etc/init.d/mysqld
    when: ansible_os_family == "RedHat" and ansible_distribution_version|int >=6
